/*
 * Copyright (c) 2025 - 2026 PCazzaniga (github.com)
 *
 *     simpleSpellCheckListener.java is part of SIMPLE.
 *
 *     SIMPLE is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     SIMPLE is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with SIMPLE.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by ANTLR 4.13.2
import org.antlr.v4.runtime.tree.ParseTreeListener;

public interface simpleSpellCheckListener extends ParseTreeListener {

	void enterFile(simpleSpellCheckParser.FileContext ctx);

	void exitFile(simpleSpellCheckParser.FileContext ctx);

	void enterElement(simpleSpellCheckParser.ElementContext ctx);

	void exitElement(simpleSpellCheckParser.ElementContext ctx);

	void enterMistake(simpleSpellCheckParser.MistakeContext ctx);

	void exitMistake(simpleSpellCheckParser.MistakeContext ctx);
}